//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoNorthwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffeestock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coffeestock()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public string ID_Stock { get; set; }
        public string Name_Stock { get; set; }
        public Nullable<decimal> Price_Stock { get; set; }
        public Nullable<int> Amount_stock { get; set; }
        public Nullable<System.DateTime> In_stock { get; set; }
        public Nullable<int> Point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
