//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoNorthwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int No_Orderdetails { get; set; }
        public Nullable<int> No_Order { get; set; }
        public string ID_Stock { get; set; }
        public Nullable<decimal> Price_Stock { get; set; }
        public Nullable<int> Amount_stock { get; set; }
        public Nullable<decimal> Total_Order { get; set; }
        public Nullable<System.DateTime> Date_Order { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual Coffeestock Coffeestock { get; set; }
        public virtual Order Order { get; set; }
    }
}
